---
stages:
  - build

include:
    - project: 'infra/pipelines/ci-templates'
      ref: master
      file:
        - '/src/oci/kaniko.yaml'
        - '/src/oci/helm.yaml'

.base:
  timeout: 15m
  tags:
    - $CI_RUNNER_TAG
  rules:
    - if: "$CI_COMMIT_TAG"

.base_build:
  stage: build
  extends: [".build_image_kaniko", ".base"]
  resource_group: build
  variables:
    CI_KANIKO_DOCKERFILE: "${CI_PROJECT_DIR}/docker/Dockerfile"
    CI_KANIKO_HARBOR_PROJECT: "infra/tools/${CI_PROJECT_NAME}"
    CI_KANIKO_DESTINATION: "${HARBOR_HOST}/${CI_KANIKO_HARBOR_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"

build:app:
  extends: [".base_build"]
