---
stages:
  - build
  - deploy

image:
  name: "${HARBOR_HOST}/infra/cd-tools/cd-tools:1.1.0-helmfile-new"

include:
    - project: 'infra/pipelines/ci-templates'
      ref: master
      file:
        - '/src/oci/kaniko.yaml'
        - '/src/oci/helm.yaml'

.yc-k8s-prod-general01:
  variables:
    KUBE_CONTEXT: "yc-k8s-prod-general01"
    VAULT_ENV_KUBE_CONFIG_BASE64: "k8s/deploy-config/yc-k8s-prod-general01/kubeconfig@infra-jobs"
    HELM_DIFF_USE_UPGRADE_DRY_RUN: false
    CI_RUNNER_TAG: k8s-prod

.base:
  timeout: 15m
  tags:
    - $CI_RUNNER_TAG
  rules:
    - if: "$CI_COMMIT_TAG"

.base_build:
  stage: build
  extends: [".build_image_kaniko", ".base"]
  resource_group: build
  variables:
    CI_KANIKO_DOCKERFILE: "${CI_PROJECT_DIR}/docker/Dockerfile"
    CI_KANIKO_HARBOR_PROJECT: "infra/tools/${CI_PROJECT_NAME}"
    CI_KANIKO_DESTINATION: "${HARBOR_HOST}/${CI_KANIKO_HARBOR_PROJECT}:${CI_COMMIT_TAG}"

build:
  extends: [".base_build"]

deploy:
  stage: deploy
  extends: [".helm_k8s_basic", ".yc-k8s-prod-general01"]
  when: manual
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "**/*.{yaml,yml,gotmpl}"
        - "*.{yaml,yml}"

  script:
    - echo "=== HELMFILE ==="
    - IMAGE_TAG=${CI_COMMIT_TAG} helmfile -f helm/helmfile.yaml --kube-context "${KUBE_CONTEXT}" -e obfuscator apply



